apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: guestbook-letsencrypt-staging
    annotations:
        kubernetes.io/ingress.class: azure/application-gateway
        certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Exact
            backend:
              service:
                name: aspnetapp
                port:
                  number: 80
  tls:
    - hosts:
      - example.com
      secretName: guestbook-secret-name
