apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: guestbook-letsencrypt-staging
    annotations:
        kubernetes.io/ingress.class: azure/application-gateway
        certmanager.k8s.io/cluster-issuer: letsencrypt-staging
spec:
    tls:
    - 
        hosts: 
            - devcluster.profitbase.biz
        secretName: guestbook-secret-name
    rules:
        - http:
            paths:
                - path: /
                    backend:
                        service:
                            name: aspnetapp
                            port:
                                number: 80
                    pathType: Exact
