apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestbook-letsencrypt-staging
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway 
    cert-manager.io/cluster-issuer: letsencrypt-staging     
    appgw.ingress.kubernetes.io/ssl-redirect: "true"       
spec:
  rules:
  - host: devcluster.profitbase.biz
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          servicename: aspnetapp
          port:
            number: 80
  tls: 
  - hosts:
    - devcluster.profitbase.biz
    secretName: banana
